[workspace]
members = [
    "crates/lzvm-artifacts",
    "crates/lzvm-accel",
    "crates/lzvm-cli",
    "crates/lzvm-crypto",
    "crates/lzvm-field",
    "crates/lzvm-pil",
    "crates/lzvm-prover",
    "crates/lzvm-setup",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SihaoLiu/Lzvm"

[profile.release]
lto = "fat"
codegen-units = 1

[profile.dev.package.lzvm-field]
opt-level = 3

[profile.dev.package.lzvm-artifacts]
opt-level = 3

[profile.dev.package.lzvm-setup]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3

[profile.test.package.lzvm-field]
opt-level = 3

[profile.test.package.lzvm-artifacts]
opt-level = 3

[profile.test.package.lzvm-setup]
opt-level = 3

[profile.test.package.sha2]
opt-level = 3
