[package]
name = "lzvm-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "lzvm_cli"
path = "src/lib.rs"

[[bin]]
name = "lzvm"
path = "src/main.rs"

[features]
default = []
cuda = ["lzvm-prover/cuda", "lzvm-setup/cuda"]

[dependencies]
lzvm-artifacts = { path = "../lzvm-artifacts", default-features = false }
lzvm-field = { path = "../lzvm-field" }
lzvm-pil = { path = "../lzvm-pil" }
lzvm-prover = { path = "../lzvm-prover" }
lzvm-setup = { path = "../lzvm-setup" }

[dev-dependencies]
