use lzvm_prover::{
    run_prove_witness_commitments_with_guest_pc_trace_segment_commitments,
    run_prove_witness_commitments_with_guest_pc_trace_segment_commitments_with_timings,
    run_prove_witness_commitments_with_guest_pc_trace_segments,
    run_prove_witness_commitments_with_guest_pc_trace_segments_with_timings, ProveExecutionPlan,
    ProveWitnessAuxiliaryInputs, ProveWitnessCommitmentError, ProveWitnessGuestPcTraceTiming,
    ProveWitnessTraceCommitments,
};

use super::timing::TimingRecorder;

mod shape_counts;

pub(super) use shape_counts::{
    record_guest_stage_root_materialization_shape, record_guest_trace_sampled_duration_counts,
};

const GUEST_TRACE_ROW_SHAPE_TOP_TIMING_NAMES: [(&str, &str); 4] = [
    (
        "guest_trace_row_shape_top_1_pattern",
        "guest_trace_row_shape_top_1_count",
    ),
    (
        "guest_trace_row_shape_top_2_pattern",
        "guest_trace_row_shape_top_2_count",
    ),
    (
        "guest_trace_row_shape_top_3_pattern",
        "guest_trace_row_shape_top_3_count",
    ),
    (
        "guest_trace_row_shape_top_4_pattern",
        "guest_trace_row_shape_top_4_count",
    ),
];

pub(super) struct GuestPcTraceWitnessRun {
    pub(super) outputs: Vec<ProveWitnessTraceCommitments>,
    pub(super) timing: Option<ProveWitnessGuestPcTraceTiming>,
}

pub(super) fn run_guest_pc_trace_witness(
    plan: &ProveExecutionPlan,
    unit_index: usize,
    auxiliary_inputs: ProveWitnessAuxiliaryInputs,
    instruction_limit: u64,
    trace_can_be_dropped: bool,
    timings_enabled: bool,
) -> Result<GuestPcTraceWitnessRun, ProveWitnessCommitmentError> {
    let mut timing = None;
    let outputs = if trace_can_be_dropped {
        if timings_enabled {
            let mut observe_timing = |observed| {
                timing = Some(observed);
            };
            run_prove_witness_commitments_with_guest_pc_trace_segment_commitments_with_timings(
                plan,
                unit_index,
                auxiliary_inputs,
                instruction_limit,
                &mut observe_timing,
            )?
        } else {
            run_prove_witness_commitments_with_guest_pc_trace_segment_commitments(
                plan,
                unit_index,
                auxiliary_inputs,
                instruction_limit,
            )?
        }
    } else {
        if timings_enabled {
            let mut observe_timing = |observed| {
                timing = Some(observed);
            };
            run_prove_witness_commitments_with_guest_pc_trace_segments_with_timings(
                plan,
                unit_index,
                auxiliary_inputs,
                instruction_limit,
                &mut observe_timing,
            )?
        } else {
            run_prove_witness_commitments_with_guest_pc_trace_segments(
                plan,
                unit_index,
                auxiliary_inputs,
                instruction_limit,
            )?
        }
    };
    Ok(GuestPcTraceWitnessRun { outputs, timing })
}

pub(super) fn record_guest_pc_trace_timing(
    timings: &mut TimingRecorder,
    timing: ProveWitnessGuestPcTraceTiming,
) {
    macro_rules! record_duration {
        ($method:ident) => {
            timings.record(
                stringify!($method).trim_end_matches("_duration"),
                timing.$method(),
            );
        };
        ($name:literal, $method:ident) => {
            timings.record($name, timing.$method());
        };
    }
    macro_rules! record_count {
        ($name:literal, $method:ident) => {
            timings.record_count($name, timing.$method());
        };
    }

    timings.record_count("guest_segment_count", timing.segment_count());
    record_duration!(guest_trace_stream_elapsed_duration);
    record_duration!(guest_trace_stream_duration);
    record_duration!(guest_trace_proof_value_prerun_duration);
    record_duration!(guest_segment_commit_duration);
    record_duration!(guest_segment_input_gap_duration);
    record_duration!(guest_segment_input_gap_max_duration);
    record_duration!(guest_segment_commit_attempt_duration);
    record_duration!(guest_segment_commit_oom_retry_duration);
    record_duration!(guest_segment_commit_worker_backpressure_join_duration);
    record_duration!(guest_segment_commit_worker_finish_join_duration);
    record_duration!(guest_trace_runner_duration);
    let runner_detail_sample_count = timing.guest_trace_runner_detail_sample_count();
    timings.record_count(
        "guest_trace_runner_detail_samples",
        runner_detail_sample_count,
    );
    timings.record_count(
        "guest_trace_runner_advance_fast_paths",
        timing.guest_trace_runner_advance_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_runner_advance_generic_fallbacks",
        timing.guest_trace_runner_advance_generic_fallback_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_hits",
        timing.guest_trace_runner_instruction_cache_hit_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_misses",
        timing.guest_trace_runner_instruction_cache_miss_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_clears",
        timing.guest_trace_runner_instruction_cache_clear_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_fcall_clears",
        timing.guest_trace_runner_instruction_cache_fcall_clear_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_dma_clears",
        timing.guest_trace_runner_instruction_cache_dma_clear_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_write_invalidation_ranges",
        timing.guest_trace_runner_instruction_cache_write_invalidation_range_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_write_invalidation_skipped_ranges",
        timing.guest_trace_runner_instruction_cache_write_invalidation_skipped_range_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_write_invalidation_probes",
        timing.guest_trace_runner_instruction_cache_write_invalidation_probe_count(),
    );
    timings.record_count(
        "guest_trace_runner_instruction_cache_invalidated_entries",
        timing.guest_trace_runner_instruction_cache_invalidated_entry_count(),
    );
    for (name, duration) in [
        (
            "guest_trace_runner_detail",
            timing.guest_trace_runner_detail_duration(),
        ),
        (
            "guest_trace_runner_prepare_instruction",
            timing.guest_trace_runner_prepare_instruction_duration(),
        ),
        (
            "guest_trace_runner_pre_boundary",
            timing.guest_trace_runner_pre_boundary_duration(),
        ),
        (
            "guest_trace_runner_row_plan",
            timing.guest_trace_runner_row_plan_duration(),
        ),
        (
            "guest_trace_runner_cache_policy",
            timing.guest_trace_runner_cache_policy_duration(),
        ),
        (
            "guest_trace_runner_advance",
            timing.guest_trace_runner_advance_duration(),
        ),
        (
            "guest_trace_runner_advance_setup",
            timing.guest_trace_runner_advance_setup_duration(),
        ),
        (
            "guest_trace_runner_advance_execute",
            timing.guest_trace_runner_advance_execute_duration(),
        ),
        (
            "guest_trace_runner_advance_report",
            timing.guest_trace_runner_advance_report_duration(),
        ),
        (
            "guest_trace_runner_cache_update",
            timing.guest_trace_runner_cache_update_duration(),
        ),
        (
            "guest_trace_runner_row_count",
            timing.guest_trace_runner_row_count_duration(),
        ),
        (
            "guest_trace_runner_post_boundary",
            timing.guest_trace_runner_post_boundary_duration(),
        ),
        (
            "guest_trace_runner_counter_update",
            timing.guest_trace_runner_counter_update_duration(),
        ),
        (
            "guest_trace_runner_timer_bookkeeping",
            timing.guest_trace_runner_timer_bookkeeping_duration(),
        ),
    ] {
        record_guest_trace_sampled_duration_counts(
            timings,
            name,
            duration,
            runner_detail_sample_count,
        );
    }
    record_duration!(guest_trace_lowerer_duration);
    record_duration!(guest_trace_lower_duration);
    record_duration!(guest_trace_report_duration);
    record_duration!(guest_trace_report_validation_duration);
    record_duration!(guest_trace_report_apply_duration);
    record_duration!(guest_trace_unit_summary_duration);
    record_duration!(
        "guest_trace_single_row_report_lower",
        guest_trace_single_row_report_duration
    );
    record_duration!(
        "guest_trace_multi_row_report_lower",
        guest_trace_multi_row_report_duration
    );
    record_duration!(
        "guest_trace_pending_dma_report_lower",
        guest_trace_pending_dma_report_duration
    );
    record_duration!(
        "guest_trace_amo_report_lower",
        guest_trace_amo_report_duration
    );
    record_duration!(
        "guest_trace_store_conditional_report_lower",
        guest_trace_store_conditional_report_duration
    );
    record_duration!(
        "guest_trace_external_op_row_lower",
        guest_trace_external_op_row_duration
    );
    record_duration!("guest_trace_copy_row_lower", guest_trace_copy_row_duration);
    record_duration!(guest_trace_report_lowering_duration);
    record_duration!(guest_trace_report_row_validation_duration);
    record_duration!(guest_trace_report_row_validation_timer_bookkeeping_duration);
    record_duration!(guest_trace_report_memory_columns_duration);
    record_duration!(guest_trace_report_source_values_duration);
    record_duration!(guest_trace_report_source_a_value_duration);
    record_duration!(guest_trace_report_source_b_value_duration);
    record_duration!(guest_trace_report_source_value_record_duration);
    record_duration!(guest_trace_report_source_immediate_read_duration);
    record_duration!(guest_trace_report_source_register_read_duration);
    record_duration!(guest_trace_report_source_memory_read_duration);
    record_duration!(guest_trace_report_source_indirect_read_duration);
    record_duration!(guest_trace_report_source_last_c_read_duration);
    record_duration!(guest_trace_copy_source_memory_read_duration);
    record_duration!(guest_trace_copy_source_indirect_read_duration);
    record_duration!(guest_trace_report_precompile_memory_duration);
    record_duration!(guest_trace_report_instruction_result_duration);
    record_duration!(guest_trace_report_next_pc_duration);
    record_duration!(guest_trace_report_register_access_duration);
    record_duration!(guest_trace_report_memory_access_duration);
    record_duration!(guest_trace_report_store_apply_duration);
    record_duration!(guest_trace_report_visit_duration);
    record_duration!(guest_trace_emit_duration);
    record_duration!(guest_trace_descriptor_duration);
    record_count!(
        "guest_segment_commit_initial_workers",
        guest_segment_commit_initial_worker_count
    );
    record_count!(
        "guest_segment_commit_effective_workers",
        guest_segment_commit_effective_worker_count
    );
    record_count!(
        "guest_segment_commit_worker_submits",
        guest_segment_commit_worker_submit_count
    );
    record_count!(
        "guest_segment_commit_worker_joins",
        guest_segment_commit_worker_join_count
    );
    record_count!(
        "guest_segment_commit_worker_backpressure_joins",
        guest_segment_commit_worker_backpressure_join_count
    );
    record_count!(
        "guest_segment_commit_worker_finish_joins",
        guest_segment_commit_worker_finish_join_count
    );
    record_count!(
        "guest_segment_commit_worker_max_in_flight",
        guest_segment_commit_worker_max_in_flight_count
    );
    record_count!(
        "guest_segment_commit_oom_retries",
        guest_segment_commit_oom_retry_count
    );
    record_count!(
        "guest_segment_input_gap_count",
        guest_segment_input_gap_count
    );
    record_count!(
        "guest_segment_commit_cuda_memory_total_bytes",
        guest_segment_commit_cuda_memory_total_byte_count
    );
    record_count!(
        "guest_segment_commit_cuda_memory_initial_free_bytes",
        guest_segment_commit_cuda_memory_initial_free_byte_count
    );
    record_count!(
        "guest_segment_commit_cuda_memory_effective_free_bytes",
        guest_segment_commit_cuda_memory_effective_free_byte_count
    );
    record_count!(
        "guest_segment_commit_cuda_memory_min_free_bytes",
        guest_segment_commit_cuda_memory_min_free_byte_count
    );
    record_duration!(guest_segment_commit_cuda_memory_sample_duration);
    record_count!(
        "guest_segment_commit_cuda_memory_samples",
        guest_segment_commit_cuda_memory_sample_count
    );
    record_count!(
        "guest_segment_commit_cuda_allocator_initial_cached_bytes",
        guest_segment_commit_cuda_allocator_initial_cached_byte_count
    );
    record_count!(
        "guest_segment_commit_cuda_allocator_effective_cached_bytes",
        guest_segment_commit_cuda_allocator_effective_cached_byte_count
    );
    let detail_sample_count = timing.guest_trace_report_detail_sample_count();
    macro_rules! record_sampled_duration_count {
        ($method:ident) => {
            record_guest_trace_sampled_duration_counts(
                timings,
                stringify!($method).trim_end_matches("_duration"),
                timing.$method(),
                detail_sample_count,
            );
        };
        ($name:literal, $method:ident) => {
            record_guest_trace_sampled_duration_counts(
                timings,
                $name,
                timing.$method(),
                detail_sample_count,
            );
        };
    }
    timings.record_count("guest_trace_report_detail_samples", detail_sample_count);
    timings.record_count(
        "guest_trace_shape_samples",
        timing.guest_trace_shape_sample_count(),
    );
    timings.record_count(
        "guest_trace_shape_sample_rows",
        timing.guest_trace_shape_sample_row_count(),
    );
    timings.record_count(
        "guest_trace_report_source_immediate_reads",
        timing.guest_trace_report_source_immediate_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_register_reads",
        timing.guest_trace_report_source_register_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_memory_reads",
        timing.guest_trace_report_source_memory_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_indirect_reads",
        timing.guest_trace_report_source_indirect_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_last_c_reads",
        timing.guest_trace_report_source_last_c_read_count(),
    );
    record_sampled_duration_count!("guest_trace_report", guest_trace_report_sample_duration);
    record_sampled_duration_count!(guest_trace_report_lowering_duration);
    record_sampled_duration_count!(guest_trace_report_row_validation_duration);
    record_sampled_duration_count!(guest_trace_report_row_validation_timer_bookkeeping_duration);
    record_sampled_duration_count!(guest_trace_report_memory_columns_duration);
    record_sampled_duration_count!(guest_trace_report_source_values_duration);
    record_sampled_duration_count!(guest_trace_report_source_a_value_duration);
    record_sampled_duration_count!(guest_trace_report_source_b_value_duration);
    record_sampled_duration_count!(guest_trace_report_source_value_record_duration);
    record_sampled_duration_count!(guest_trace_report_source_immediate_read_duration);
    record_sampled_duration_count!(guest_trace_report_source_register_read_duration);
    record_sampled_duration_count!(guest_trace_report_source_memory_read_duration);
    record_sampled_duration_count!(guest_trace_report_source_indirect_read_duration);
    record_sampled_duration_count!(guest_trace_report_source_last_c_read_duration);
    record_sampled_duration_count!(guest_trace_copy_source_memory_read_duration);
    record_sampled_duration_count!(guest_trace_copy_source_indirect_read_duration);
    record_sampled_duration_count!(guest_trace_report_precompile_memory_duration);
    record_sampled_duration_count!(guest_trace_report_instruction_result_duration);
    record_sampled_duration_count!(guest_trace_report_next_pc_duration);
    record_sampled_duration_count!(guest_trace_report_register_access_duration);
    record_sampled_duration_count!(guest_trace_report_memory_access_duration);
    record_sampled_duration_count!(guest_trace_report_store_apply_duration);
    record_sampled_duration_count!(guest_trace_report_visit_duration);
    record_sampled_duration_count!(guest_trace_descriptor_duration);
    timings.record(
        "guest_trace_seed_direct_lift",
        timing.guest_trace_seed_direct_lift_duration(),
    );
    timings.record(
        "guest_trace_seed_full_advance",
        timing.guest_trace_seed_full_advance_duration(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_attempts",
        timing.guest_trace_seed_direct_lift_attempt_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_successes",
        timing.guest_trace_seed_direct_lift_success_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_empty_segments",
        timing.guest_trace_seed_direct_lift_empty_segment_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_pending_dma_single_reports",
        timing.guest_trace_seed_direct_lift_pending_dma_single_report_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_amo_boundaries",
        timing.guest_trace_seed_direct_lift_amo_boundary_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_store_conditional_boundaries",
        timing.guest_trace_seed_direct_lift_store_conditional_boundary_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_dma_prepare_missing_lookaheads",
        timing.guest_trace_seed_direct_lift_dma_prepare_missing_lookahead_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_boundary_c_unavailable",
        timing.guest_trace_seed_direct_lift_boundary_c_unavailable_count(),
    );
    timings.record_count(
        "guest_trace_seed_full_advances",
        timing.guest_trace_seed_full_advance_count(),
    );
    timings.record_count("guest_trace_reports", timing.guest_trace_report_count());
    timings.record_count(
        "guest_trace_report_rows",
        timing.guest_trace_report_row_count(),
    );
    timings.record_count(
        "guest_trace_main_report_fast_paths",
        timing.guest_trace_main_report_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_main_report_generic_fallbacks",
        timing.guest_trace_main_report_generic_fallback_count(),
    );
    timings.record_count(
        "guest_trace_main_report_fcall_result_fast_paths",
        timing.guest_trace_main_report_fcall_result_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_main_report_load_copy_fast_paths",
        timing.guest_trace_main_report_load_copy_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_main_report_load_sign_extend_fast_paths",
        timing.guest_trace_main_report_load_sign_extend_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_main_report_no_memory_fast_paths",
        timing.guest_trace_main_report_no_memory_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_main_report_store_copy_fast_paths",
        timing.guest_trace_main_report_store_copy_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_main_report_simple_copy_fast_paths",
        timing.guest_trace_main_report_simple_copy_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_main_report_jump_fast_paths",
        timing.guest_trace_main_report_jump_fast_path_count(),
    );
    timings.record_count(
        "guest_trace_stream_start_sent",
        timing.guest_trace_stream_start_sent_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_sent",
        timing.guest_trace_report_chunk_sent_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_received",
        timing.guest_trace_report_chunk_received_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_reports",
        timing.guest_trace_report_chunk_report_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_rows",
        timing.guest_trace_report_chunk_row_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_max_queued",
        timing.guest_trace_report_chunk_max_queued_count(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_capacity",
        timing.guest_trace_runner_report_buffer_capacity(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_max_capacity",
        timing.guest_trace_runner_report_buffer_max_capacity(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_excess_capacity",
        timing.guest_trace_runner_report_buffer_excess_capacity(),
    );
    timings.record_count(
        "guest_trace_report_buffer_capacity",
        timing.guest_trace_report_buffer_capacity(),
    );
    timings.record_count(
        "guest_trace_report_buffer_max_capacity",
        timing.guest_trace_report_buffer_max_capacity(),
    );
    timings.record_count(
        "guest_trace_report_buffer_excess_capacity",
        timing.guest_trace_report_buffer_excess_capacity(),
    );
    timings.record_count(
        "guest_trace_report_record_size_bytes",
        timing.guest_trace_report_record_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_instruction_size_bytes",
        timing.guest_trace_report_instruction_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_register_write_list_size_bytes",
        timing.guest_trace_report_register_write_list_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_memory_access_list_size_bytes",
        timing.guest_trace_report_memory_access_list_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_precompile_access_list_size_bytes",
        timing.guest_trace_report_precompile_access_list_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_storage_bytes",
        timing.guest_trace_report_storage_bytes(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_capacity_bytes",
        timing.guest_trace_runner_report_buffer_capacity_bytes(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_excess_bytes",
        timing.guest_trace_runner_report_buffer_excess_bytes(),
    );
    timings.record_count(
        "guest_trace_report_buffer_capacity_bytes",
        timing.guest_trace_report_buffer_capacity_bytes(),
    );
    timings.record_count(
        "guest_trace_report_buffer_excess_bytes",
        timing.guest_trace_report_buffer_excess_bytes(),
    );
    timings.record_count(
        "guest_trace_descriptor_rows",
        timing.guest_trace_descriptor_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_compact_rows",
        timing.guest_trace_descriptor_compact_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_wide_rows",
        timing.guest_trace_descriptor_wide_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_unpaired_values",
        timing.guest_trace_descriptor_unpaired_value_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_unpaired_high32_nonzero_values",
        timing.guest_trace_descriptor_unpaired_high32_nonzero_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_unpaired_high32_nonzero_rows",
        timing.guest_trace_descriptor_unpaired_high32_nonzero_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_high32_stats_enabled",
        usize::from(timing.guest_trace_descriptor_high32_stats_enabled()),
    );
    let [descriptor_high32_a_values, descriptor_high32_b_values, descriptor_high32_c_values, descriptor_high32_a_payload_values, descriptor_high32_b_payload_values, descriptor_high32_store_payload_values, descriptor_high32_store_prev_value_values] =
        timing.guest_trace_descriptor_high32_field_counts();
    for (name, count) in [
        (
            "guest_trace_descriptor_high32_a_values",
            descriptor_high32_a_values,
        ),
        (
            "guest_trace_descriptor_high32_b_values",
            descriptor_high32_b_values,
        ),
        (
            "guest_trace_descriptor_high32_c_values",
            descriptor_high32_c_values,
        ),
        (
            "guest_trace_descriptor_high32_a_payload_values",
            descriptor_high32_a_payload_values,
        ),
        (
            "guest_trace_descriptor_high32_b_payload_values",
            descriptor_high32_b_payload_values,
        ),
        (
            "guest_trace_descriptor_high32_store_payload_values",
            descriptor_high32_store_payload_values,
        ),
        (
            "guest_trace_descriptor_high32_store_prev_value_values",
            descriptor_high32_store_prev_value_values,
        ),
    ] {
        timings.record_count(name, count);
    }
    let [descriptor_high32_rows_with_0_fields, descriptor_high32_rows_with_1_fields, descriptor_high32_rows_with_2_fields, descriptor_high32_rows_with_3_fields, descriptor_high32_rows_with_4_fields, descriptor_high32_rows_with_5_fields, descriptor_high32_rows_with_6_fields, descriptor_high32_rows_with_7_fields] =
        timing.guest_trace_descriptor_high32_row_field_histogram();
    for (name, count) in [
        (
            "guest_trace_descriptor_high32_rows_with_0_fields",
            descriptor_high32_rows_with_0_fields,
        ),
        (
            "guest_trace_descriptor_high32_rows_with_1_fields",
            descriptor_high32_rows_with_1_fields,
        ),
        (
            "guest_trace_descriptor_high32_rows_with_2_fields",
            descriptor_high32_rows_with_2_fields,
        ),
        (
            "guest_trace_descriptor_high32_rows_with_3_fields",
            descriptor_high32_rows_with_3_fields,
        ),
        (
            "guest_trace_descriptor_high32_rows_with_4_fields",
            descriptor_high32_rows_with_4_fields,
        ),
        (
            "guest_trace_descriptor_high32_rows_with_5_fields",
            descriptor_high32_rows_with_5_fields,
        ),
        (
            "guest_trace_descriptor_high32_rows_with_6_fields",
            descriptor_high32_rows_with_6_fields,
        ),
        (
            "guest_trace_descriptor_high32_rows_with_7_fields",
            descriptor_high32_rows_with_7_fields,
        ),
    ] {
        timings.record_count(name, count);
    }
    timings.record_count(
        "guest_trace_single_row_reports",
        timing.guest_trace_single_row_report_count(),
    );
    timings.record_count(
        "guest_trace_multi_row_reports",
        timing.guest_trace_multi_row_report_count(),
    );
    timings.record_count(
        "guest_trace_pending_dma_reports",
        timing.guest_trace_pending_dma_report_count(),
    );
    timings.record_count(
        "guest_trace_amo_reports",
        timing.guest_trace_amo_report_count(),
    );
    timings.record_count(
        "guest_trace_store_conditional_reports",
        timing.guest_trace_store_conditional_report_count(),
    );
    timings.record_count(
        "guest_trace_external_op_rows",
        timing.guest_trace_external_op_row_count(),
    );
    timings.record_count(
        "guest_trace_external_op_runs",
        timing.guest_trace_external_op_run_count(),
    );
    timings.record_count(
        "guest_trace_external_op_max_run",
        timing.guest_trace_external_op_max_run_count(),
    );
    timings.record_count("guest_trace_copy_rows", timing.guest_trace_copy_row_count());
    timings.record_count(
        "guest_trace_copy_memory_source_rows",
        timing.guest_trace_copy_memory_source_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_indirect_memory_rows",
        timing.guest_trace_copy_indirect_memory_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_register_store_rows",
        timing.guest_trace_copy_register_store_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_memory_store_rows",
        timing.guest_trace_copy_memory_store_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_no_store_rows",
        timing.guest_trace_copy_no_store_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_no_memory_rows",
        timing.guest_trace_copy_no_memory_row_count(),
    );
    timings.record_count("guest_trace_copy_runs", timing.guest_trace_copy_run_count());
    timings.record_count(
        "guest_trace_copy_max_run",
        timing.guest_trace_copy_max_run_count(),
    );
    timings.record_count("guest_trace_flag_rows", timing.guest_trace_flag_row_count());
    timings.record_count(
        "guest_trace_precompile_rows",
        timing.guest_trace_precompile_row_count(),
    );
    timings.record_count(
        "guest_trace_indirect_memory_rows",
        timing.guest_trace_indirect_memory_row_count(),
    );
    timings.record_count(
        "guest_trace_register_source_reads",
        timing.guest_trace_register_source_read_count(),
    );
    timings.record_count(
        "guest_trace_memory_source_reads",
        timing.guest_trace_memory_source_read_count(),
    );
    timings.record_count(
        "guest_trace_copy_source_memory_reads",
        timing.guest_trace_copy_source_memory_read_count(),
    );
    timings.record_count(
        "guest_trace_copy_source_indirect_reads",
        timing.guest_trace_copy_source_indirect_read_count(),
    );
    timings.record_count(
        "guest_trace_register_store_rows",
        timing.guest_trace_register_store_row_count(),
    );
    timings.record_count(
        "guest_trace_memory_store_rows",
        timing.guest_trace_memory_store_row_count(),
    );
    timings.record_count(
        "guest_trace_no_store_rows",
        timing.guest_trace_no_store_row_count(),
    );
    for (&(pattern_name, count_name), (pattern, count)) in GUEST_TRACE_ROW_SHAPE_TOP_TIMING_NAMES
        .iter()
        .zip(timing.guest_trace_row_shape_top_patterns().into_iter())
    {
        timings.record_count(pattern_name, pattern as usize);
        timings.record_count(count_name, count);
    }
    timings.record(
        "guest_trace_pending_send_wait",
        timing.guest_trace_pending_send_wait_duration(),
    );
    timings.record(
        "guest_trace_pending_receive_wait",
        timing.guest_trace_pending_receive_wait_duration(),
    );
    timings.record(
        "guest_trace_segment_send_wait",
        timing.guest_trace_segment_send_wait_duration(),
    );
    timings.record(
        "guest_trace_segment_receive_wait",
        timing.guest_trace_segment_receive_wait_duration(),
    );
    timings.record_count(
        "guest_trace_segment_replay_count",
        timing.guest_trace_segment_replay_count(),
    );
    timings.record_count(
        "guest_trace_segment_replay_snapshot_capture_count",
        timing.guest_trace_segment_replay_snapshot_capture_count(),
    );
    timings.record(
        "guest_trace_segment_replay_snapshot_capture",
        timing.guest_trace_segment_replay_snapshot_capture_duration(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_workers",
        timing.guest_trace_parallel_lower_worker_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_dispatched",
        timing.guest_trace_parallel_lower_dispatched_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_received",
        timing.guest_trace_parallel_lower_received_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_emitted",
        timing.guest_trace_parallel_lower_emitted_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_max_reorder",
        timing.guest_trace_parallel_lower_max_reorder_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_snapshot_replay_count",
        timing.guest_trace_parallel_lower_snapshot_replay_count(),
    );
    timings.record(
        "guest_trace_parallel_lower_snapshot_replay",
        timing.guest_trace_parallel_lower_snapshot_replay_duration(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_report_elided_count",
        timing.guest_trace_parallel_lower_report_elided_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_stream_segments",
        timing.guest_trace_parallel_lower_stream_segment_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_stream_chunks",
        timing.guest_trace_parallel_lower_stream_chunk_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_stream_fallbacks",
        timing.guest_trace_parallel_lower_stream_fallback_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_stream_retained_reports",
        timing.guest_trace_parallel_lower_stream_retained_report_count(),
    );
    timings.record_count(
        "guest_trace_owned_streaming_lower_segments",
        timing.guest_trace_owned_streaming_lower_segment_count(),
    );
    timings.record(
        "guest_trace_parallel_lower_stream_chunk_process",
        timing.guest_trace_parallel_lower_stream_chunk_process_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_job_receive_wait",
        timing.guest_trace_parallel_lower_job_receive_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_result_send_wait",
        timing.guest_trace_parallel_lower_result_send_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_dispatch_wait",
        timing.guest_trace_parallel_lower_dispatch_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_stream_start_dispatch_wait",
        timing.guest_trace_parallel_lower_stream_start_dispatch_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_stream_chunk_dispatch_wait",
        timing.guest_trace_parallel_lower_stream_chunk_dispatch_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_stream_segment_dispatch_wait",
        timing.guest_trace_parallel_lower_stream_segment_dispatch_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_stream_finish_dispatch_wait",
        timing.guest_trace_parallel_lower_stream_finish_dispatch_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_result_receive_wait",
        timing.guest_trace_parallel_lower_result_receive_wait_duration(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_dispatch_blocked_count",
        timing.guest_trace_parallel_lower_dispatch_blocked_count(),
    );
    timings.record(
        "guest_device_source_build",
        timing.guest_device_source_build_duration(),
    );
    timings.record(
        "guest_device_source_descriptor_upload",
        timing.guest_device_source_descriptor_upload_duration(),
    );
    timings.record_count(
        "guest_device_source_descriptor_upload_bytes",
        timing.guest_device_source_descriptor_upload_byte_count(),
    );
    timings.record_count(
        "guest_device_source_descriptor_upload_words",
        timing.guest_device_source_descriptor_upload_word_count(),
    );
    timings.record_count(
        "guest_device_source_descriptor_upload_rows",
        timing.guest_device_source_descriptor_upload_row_count(),
    );
    timings.record_count(
        "guest_device_source_descriptor_stream_ingress",
        timing.guest_device_source_descriptor_stream_ingress_count(),
    );
    timings.record(
        "guest_device_source_trace_expand",
        timing.guest_device_source_trace_expand_duration(),
    );
    timings.record(
        "guest_stage_source_upload",
        timing.guest_stage_source_upload_duration(),
    );
    timings.record_count(
        "guest_stage_source_cpu_fast_path_count",
        timing.guest_stage_source_cpu_fast_path_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_attempts",
        timing.guest_stage_source_retention_attempt_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_retained",
        timing.guest_stage_source_retention_retained_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_rejected",
        timing.guest_stage_source_retention_rejected_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_retained_bytes",
        timing.guest_stage_source_retention_retained_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_rejected_bytes",
        timing.guest_stage_source_retention_rejected_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_max_retained_bytes",
        timing.guest_stage_source_retention_max_retained_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_max_rejected_bytes",
        timing.guest_stage_source_retention_max_rejected_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_limit_bytes",
        timing.guest_stage_source_retention_limit_byte_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_attempts",
        timing.guest_descriptor_buffer_retention_attempt_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_retained",
        timing.guest_descriptor_buffer_retention_retained_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_rejected",
        timing.guest_descriptor_buffer_retention_rejected_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_retained_bytes",
        timing.guest_descriptor_buffer_retention_retained_byte_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_rejected_bytes",
        timing.guest_descriptor_buffer_retention_rejected_byte_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_limit_bytes",
        timing.guest_descriptor_buffer_retention_limit_byte_count(),
    );
    timings.record(
        "guest_retained_trace_artifact",
        timing.guest_retained_trace_artifact_duration(),
    );
    timings.record(
        "guest_regular_constraints",
        timing.guest_regular_constraint_duration(),
    );
    timings.record("guest_regular_hints", timing.guest_regular_hint_duration());
    timings.record("guest_stage_commit", timing.guest_stage_commit_duration());
    timings.record(
        "guest_stage_trace_extract",
        timing.guest_stage_trace_extract_duration(),
    );
    timings.record(
        "guest_stage_leaf_extend_work",
        timing.guest_stage_leaf_extend_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_work",
        timing.guest_stage_leaf_setup_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_prepare",
        timing.guest_stage_leaf_setup_prepare_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_output_alloc",
        timing.guest_stage_leaf_setup_output_alloc_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_workspace_alloc",
        timing.guest_stage_leaf_setup_workspace_alloc_duration(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_output_alloc_bytes",
        timing.guest_stage_leaf_setup_output_alloc_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_workspace_alloc_bytes",
        timing.guest_stage_leaf_setup_workspace_alloc_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_output_alloc_count",
        timing.guest_stage_leaf_setup_output_alloc_count(),
    );
    timings.record_count(
        "guest_stage_leaf_output_cache_hits",
        timing.guest_stage_leaf_output_cache_hit_count(),
    );
    timings.record_count(
        "guest_stage_leaf_output_cache_misses",
        timing.guest_stage_leaf_output_cache_miss_count(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_workspace_alloc_count",
        timing.guest_stage_leaf_setup_workspace_alloc_count(),
    );
    timings.record(
        "guest_stage_leaf_upload_work",
        timing.guest_stage_leaf_upload_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_kernel_work",
        timing.guest_stage_leaf_kernel_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_download_work",
        timing.guest_stage_leaf_download_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_validate_work",
        timing.guest_stage_leaf_validate_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_hash_work",
        timing.guest_stage_leaf_hash_work_duration(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_rows",
        timing.guest_stage_leaf_hash_row_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_bytes",
        timing.guest_stage_leaf_hash_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity2_rows",
        timing.guest_stage_leaf_hash_arity2_row_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity2_bytes",
        timing.guest_stage_leaf_hash_arity2_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity4_rows",
        timing.guest_stage_leaf_hash_arity4_row_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity4_bytes",
        timing.guest_stage_leaf_hash_arity4_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_calls",
        timing.guest_stage_leaf_coset_extend_call_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_output_bytes",
        timing.guest_stage_leaf_coset_extend_output_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_columns",
        timing.guest_stage_leaf_coset_extend_column_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_max_columns",
        timing.guest_stage_leaf_coset_extend_max_column_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_ntt_launches",
        timing.guest_stage_leaf_coset_extend_ntt_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_bit_reverse_launches",
        timing.guest_stage_leaf_coset_extend_bit_reverse_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_ntt_stage_launches",
        timing.guest_stage_leaf_coset_extend_ntt_stage_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_ntt_block_twiddle_launches",
        timing.guest_stage_leaf_coset_extend_ntt_block_twiddle_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_normalize_launches",
        timing.guest_stage_leaf_coset_extend_normalize_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_pack_launches",
        timing.guest_stage_leaf_coset_extend_pack_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_unpack_launches",
        timing.guest_stage_leaf_coset_extend_unpack_launch_count(),
    );
    timings.record(
        "guest_stage_tree_commit_work",
        timing.guest_stage_tree_commit_work_duration(),
    );
    timings.record(
        "guest_stage_tree_commit_checkpoint_work",
        timing.guest_stage_tree_commit_checkpoint_work_duration(),
    );
    timings.record(
        "guest_stage_tree_commit_root_work",
        timing.guest_stage_tree_commit_root_work_duration(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_count",
        timing.guest_stage_tree_commit_root_count(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_bytes",
        timing.guest_stage_tree_commit_root_byte_count(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_materialization_groups",
        timing.guest_stage_tree_commit_root_materialization_group_count(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_materialization_max_group_size",
        timing.guest_stage_tree_commit_root_materialization_max_group_size(),
    );
    record_guest_stage_root_materialization_shape(
        timings,
        timing.guest_stage_tree_commit_root_count(),
        timing.guest_stage_tree_commit_root_materialization_group_count(),
        timing.guest_stage_tree_commit_root_materialization_max_group_size(),
    );
    timings.record(
        "guest_stage_tree_commit_retain_work",
        timing.guest_stage_tree_commit_retain_work_duration(),
    );
    for stage_timing in timing.guest_stage_timings() {
        let stage_index = stage_timing.stage_index();
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_extend_work"),
            stage_timing.leaf_extend_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_work"),
            stage_timing.leaf_setup_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_prepare"),
            stage_timing.leaf_setup_prepare_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_output_alloc"),
            stage_timing.leaf_setup_output_alloc_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_workspace_alloc"),
            stage_timing.leaf_setup_workspace_alloc_duration(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_output_alloc_bytes"),
            stage_timing.leaf_setup_output_alloc_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_workspace_alloc_bytes"),
            stage_timing.leaf_setup_workspace_alloc_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_output_alloc_count"),
            stage_timing.leaf_setup_output_alloc_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_output_cache_hits"),
            stage_timing.leaf_output_cache_hit_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_output_cache_misses"),
            stage_timing.leaf_output_cache_miss_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_workspace_alloc_count"),
            stage_timing.leaf_setup_workspace_alloc_count(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_upload_work"),
            stage_timing.leaf_upload_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_kernel_work"),
            stage_timing.leaf_kernel_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_download_work"),
            stage_timing.leaf_download_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_validate_work"),
            stage_timing.leaf_validate_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_work"),
            stage_timing.leaf_hash_work_duration(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_rows"),
            stage_timing.leaf_hash_row_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_bytes"),
            stage_timing.leaf_hash_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity2_rows"),
            stage_timing.leaf_hash_arity2_row_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity2_bytes"),
            stage_timing.leaf_hash_arity2_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity4_rows"),
            stage_timing.leaf_hash_arity4_row_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity4_bytes"),
            stage_timing.leaf_hash_arity4_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_calls"),
            stage_timing.leaf_coset_extend_call_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_output_bytes"),
            stage_timing.leaf_coset_extend_output_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_columns"),
            stage_timing.leaf_coset_extend_column_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_max_columns"),
            stage_timing.leaf_coset_extend_max_column_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_ntt_launches"),
            stage_timing.leaf_coset_extend_ntt_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_bit_reverse_launches"),
            stage_timing.leaf_coset_extend_bit_reverse_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_ntt_stage_launches"),
            stage_timing.leaf_coset_extend_ntt_stage_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_ntt_block_twiddle_launches"),
            stage_timing.leaf_coset_extend_ntt_block_twiddle_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_normalize_launches"),
            stage_timing.leaf_coset_extend_normalize_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_pack_launches"),
            stage_timing.leaf_coset_extend_pack_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_unpack_launches"),
            stage_timing.leaf_coset_extend_unpack_launch_count(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_work"),
            stage_timing.tree_commit_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_checkpoint_work"),
            stage_timing.tree_commit_checkpoint_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_root_work"),
            stage_timing.tree_commit_root_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_retain_work"),
            stage_timing.tree_commit_retain_work_duration(),
        );
    }
}
