use lzvm_prover::{
    run_prove_witness_commitments_with_guest_pc_trace_segment_commitments,
    run_prove_witness_commitments_with_guest_pc_trace_segment_commitments_with_timings,
    run_prove_witness_commitments_with_guest_pc_trace_segments, ProveExecutionPlan,
    ProveWitnessAuxiliaryInputs, ProveWitnessCommitmentError, ProveWitnessGuestPcTraceTiming,
    ProveWitnessTraceCommitments,
};

use super::timing::TimingRecorder;
use std::time::Duration;

pub(super) struct GuestPcTraceWitnessRun {
    pub(super) outputs: Vec<ProveWitnessTraceCommitments>,
    pub(super) timing: Option<ProveWitnessGuestPcTraceTiming>,
}

pub(super) fn run_guest_pc_trace_witness(
    plan: &ProveExecutionPlan,
    unit_index: usize,
    auxiliary_inputs: ProveWitnessAuxiliaryInputs,
    instruction_limit: u64,
    trace_can_be_dropped: bool,
    timings_enabled: bool,
) -> Result<GuestPcTraceWitnessRun, ProveWitnessCommitmentError> {
    let mut timing = None;
    let outputs = if trace_can_be_dropped {
        if timings_enabled {
            let mut observe_timing = |observed| {
                timing = Some(observed);
            };
            run_prove_witness_commitments_with_guest_pc_trace_segment_commitments_with_timings(
                plan,
                unit_index,
                auxiliary_inputs,
                instruction_limit,
                &mut observe_timing,
            )?
        } else {
            run_prove_witness_commitments_with_guest_pc_trace_segment_commitments(
                plan,
                unit_index,
                auxiliary_inputs,
                instruction_limit,
            )?
        }
    } else {
        run_prove_witness_commitments_with_guest_pc_trace_segments(
            plan,
            unit_index,
            auxiliary_inputs,
            instruction_limit,
        )?
    };
    Ok(GuestPcTraceWitnessRun { outputs, timing })
}

pub(super) fn record_guest_pc_trace_timing(
    timings: &mut TimingRecorder,
    timing: ProveWitnessGuestPcTraceTiming,
) {
    timings.record_count("guest_segment_count", timing.segment_count());
    timings.record(
        "guest_trace_stream_elapsed",
        timing.guest_trace_stream_elapsed_duration(),
    );
    timings.record("guest_trace_stream", timing.guest_trace_stream_duration());
    timings.record(
        "guest_trace_proof_value_prerun",
        timing.guest_trace_proof_value_prerun_duration(),
    );
    timings.record(
        "guest_segment_commit",
        timing.guest_segment_commit_duration(),
    );
    timings.record(
        "guest_segment_commit_attempt",
        timing.guest_segment_commit_attempt_duration(),
    );
    timings.record(
        "guest_segment_commit_oom_retry",
        timing.guest_segment_commit_oom_retry_duration(),
    );
    timings.record_count(
        "guest_segment_commit_initial_workers",
        timing.guest_segment_commit_initial_worker_count(),
    );
    timings.record_count(
        "guest_segment_commit_effective_workers",
        timing.guest_segment_commit_effective_worker_count(),
    );
    timings.record_count(
        "guest_segment_commit_worker_submits",
        timing.guest_segment_commit_worker_submit_count(),
    );
    timings.record_count(
        "guest_segment_commit_worker_joins",
        timing.guest_segment_commit_worker_join_count(),
    );
    timings.record_count(
        "guest_segment_commit_worker_backpressure_joins",
        timing.guest_segment_commit_worker_backpressure_join_count(),
    );
    timings.record(
        "guest_segment_commit_worker_backpressure_join",
        timing.guest_segment_commit_worker_backpressure_join_duration(),
    );
    timings.record_count(
        "guest_segment_commit_worker_finish_joins",
        timing.guest_segment_commit_worker_finish_join_count(),
    );
    timings.record(
        "guest_segment_commit_worker_finish_join",
        timing.guest_segment_commit_worker_finish_join_duration(),
    );
    timings.record_count(
        "guest_segment_commit_worker_max_in_flight",
        timing.guest_segment_commit_worker_max_in_flight_count(),
    );
    timings.record_count(
        "guest_segment_commit_oom_retries",
        timing.guest_segment_commit_oom_retry_count(),
    );
    timings.record_count(
        "guest_segment_commit_cuda_memory_total_bytes",
        timing.guest_segment_commit_cuda_memory_total_byte_count(),
    );
    timings.record_count(
        "guest_segment_commit_cuda_memory_initial_free_bytes",
        timing.guest_segment_commit_cuda_memory_initial_free_byte_count(),
    );
    timings.record_count(
        "guest_segment_commit_cuda_memory_effective_free_bytes",
        timing.guest_segment_commit_cuda_memory_effective_free_byte_count(),
    );
    timings.record_count(
        "guest_segment_commit_cuda_memory_min_free_bytes",
        timing.guest_segment_commit_cuda_memory_min_free_byte_count(),
    );
    timings.record_count(
        "guest_segment_commit_cuda_allocator_initial_cached_bytes",
        timing.guest_segment_commit_cuda_allocator_initial_cached_byte_count(),
    );
    timings.record_count(
        "guest_segment_commit_cuda_allocator_effective_cached_bytes",
        timing.guest_segment_commit_cuda_allocator_effective_cached_byte_count(),
    );
    timings.record("guest_trace_runner", timing.guest_trace_runner_duration());
    timings.record("guest_trace_lowerer", timing.guest_trace_lowerer_duration());
    timings.record("guest_trace_lower", timing.guest_trace_lower_duration());
    timings.record("guest_trace_report", timing.guest_trace_report_duration());
    timings.record(
        "guest_trace_report_validation",
        timing.guest_trace_report_validation_duration(),
    );
    timings.record(
        "guest_trace_single_row_report_lower",
        timing.guest_trace_single_row_report_duration(),
    );
    timings.record(
        "guest_trace_multi_row_report_lower",
        timing.guest_trace_multi_row_report_duration(),
    );
    timings.record(
        "guest_trace_pending_dma_report_lower",
        timing.guest_trace_pending_dma_report_duration(),
    );
    timings.record(
        "guest_trace_amo_report_lower",
        timing.guest_trace_amo_report_duration(),
    );
    timings.record(
        "guest_trace_store_conditional_report_lower",
        timing.guest_trace_store_conditional_report_duration(),
    );
    timings.record(
        "guest_trace_external_op_row_lower",
        timing.guest_trace_external_op_row_duration(),
    );
    timings.record(
        "guest_trace_copy_row_lower",
        timing.guest_trace_copy_row_duration(),
    );
    timings.record(
        "guest_trace_report_lowering",
        timing.guest_trace_report_lowering_duration(),
    );
    timings.record(
        "guest_trace_report_row_validation",
        timing.guest_trace_report_row_validation_duration(),
    );
    timings.record(
        "guest_trace_report_memory_columns",
        timing.guest_trace_report_memory_columns_duration(),
    );
    timings.record(
        "guest_trace_report_source_values",
        timing.guest_trace_report_source_values_duration(),
    );
    timings.record(
        "guest_trace_report_source_a_value",
        timing.guest_trace_report_source_a_value_duration(),
    );
    timings.record(
        "guest_trace_report_source_b_value",
        timing.guest_trace_report_source_b_value_duration(),
    );
    timings.record(
        "guest_trace_report_source_immediate_read",
        timing.guest_trace_report_source_immediate_read_duration(),
    );
    timings.record(
        "guest_trace_report_source_register_read",
        timing.guest_trace_report_source_register_read_duration(),
    );
    timings.record(
        "guest_trace_report_source_memory_read",
        timing.guest_trace_report_source_memory_read_duration(),
    );
    timings.record(
        "guest_trace_report_source_indirect_read",
        timing.guest_trace_report_source_indirect_read_duration(),
    );
    timings.record(
        "guest_trace_report_source_last_c_read",
        timing.guest_trace_report_source_last_c_read_duration(),
    );
    timings.record(
        "guest_trace_copy_source_memory_read",
        timing.guest_trace_copy_source_memory_read_duration(),
    );
    timings.record(
        "guest_trace_copy_source_indirect_read",
        timing.guest_trace_copy_source_indirect_read_duration(),
    );
    timings.record(
        "guest_trace_report_precompile_memory",
        timing.guest_trace_report_precompile_memory_duration(),
    );
    timings.record(
        "guest_trace_report_instruction_result",
        timing.guest_trace_report_instruction_result_duration(),
    );
    timings.record(
        "guest_trace_report_next_pc",
        timing.guest_trace_report_next_pc_duration(),
    );
    timings.record(
        "guest_trace_report_register_access",
        timing.guest_trace_report_register_access_duration(),
    );
    timings.record(
        "guest_trace_report_memory_access",
        timing.guest_trace_report_memory_access_duration(),
    );
    timings.record(
        "guest_trace_report_store_apply",
        timing.guest_trace_report_store_apply_duration(),
    );
    timings.record(
        "guest_trace_report_visit",
        timing.guest_trace_report_visit_duration(),
    );
    timings.record("guest_trace_emit", timing.guest_trace_emit_duration());
    timings.record(
        "guest_trace_descriptor",
        timing.guest_trace_descriptor_duration(),
    );
    let detail_sample_count = timing.guest_trace_report_detail_sample_count();
    timings.record_count("guest_trace_report_detail_samples", detail_sample_count);
    timings.record_count(
        "guest_trace_report_source_immediate_reads",
        timing.guest_trace_report_source_immediate_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_register_reads",
        timing.guest_trace_report_source_register_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_memory_reads",
        timing.guest_trace_report_source_memory_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_indirect_reads",
        timing.guest_trace_report_source_indirect_read_count(),
    );
    timings.record_count(
        "guest_trace_report_source_last_c_reads",
        timing.guest_trace_report_source_last_c_read_count(),
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report",
        timing.guest_trace_report_sample_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_lowering",
        timing.guest_trace_report_lowering_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_row_validation",
        timing.guest_trace_report_row_validation_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_memory_columns",
        timing.guest_trace_report_memory_columns_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_values",
        timing.guest_trace_report_source_values_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_a_value",
        timing.guest_trace_report_source_a_value_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_b_value",
        timing.guest_trace_report_source_b_value_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_immediate_read",
        timing.guest_trace_report_source_immediate_read_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_register_read",
        timing.guest_trace_report_source_register_read_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_memory_read",
        timing.guest_trace_report_source_memory_read_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_indirect_read",
        timing.guest_trace_report_source_indirect_read_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_source_last_c_read",
        timing.guest_trace_report_source_last_c_read_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_copy_source_memory_read",
        timing.guest_trace_copy_source_memory_read_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_copy_source_indirect_read",
        timing.guest_trace_copy_source_indirect_read_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_precompile_memory",
        timing.guest_trace_report_precompile_memory_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_instruction_result",
        timing.guest_trace_report_instruction_result_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_next_pc",
        timing.guest_trace_report_next_pc_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_register_access",
        timing.guest_trace_report_register_access_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_memory_access",
        timing.guest_trace_report_memory_access_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_store_apply",
        timing.guest_trace_report_store_apply_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_report_visit",
        timing.guest_trace_report_visit_duration(),
        detail_sample_count,
    );
    record_guest_trace_sampled_duration_counts(
        timings,
        "guest_trace_descriptor",
        timing.guest_trace_descriptor_duration(),
        detail_sample_count,
    );
    timings.record(
        "guest_trace_seed_direct_lift",
        timing.guest_trace_seed_direct_lift_duration(),
    );
    timings.record(
        "guest_trace_seed_full_advance",
        timing.guest_trace_seed_full_advance_duration(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_attempts",
        timing.guest_trace_seed_direct_lift_attempt_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_successes",
        timing.guest_trace_seed_direct_lift_success_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_empty_segments",
        timing.guest_trace_seed_direct_lift_empty_segment_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_pending_dma_single_reports",
        timing.guest_trace_seed_direct_lift_pending_dma_single_report_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_amo_boundaries",
        timing.guest_trace_seed_direct_lift_amo_boundary_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_store_conditional_boundaries",
        timing.guest_trace_seed_direct_lift_store_conditional_boundary_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_dma_prepare_missing_lookaheads",
        timing.guest_trace_seed_direct_lift_dma_prepare_missing_lookahead_count(),
    );
    timings.record_count(
        "guest_trace_seed_direct_lift_boundary_c_unavailable",
        timing.guest_trace_seed_direct_lift_boundary_c_unavailable_count(),
    );
    timings.record_count(
        "guest_trace_seed_full_advances",
        timing.guest_trace_seed_full_advance_count(),
    );
    timings.record_count("guest_trace_reports", timing.guest_trace_report_count());
    timings.record_count(
        "guest_trace_report_rows",
        timing.guest_trace_report_row_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_sent",
        timing.guest_trace_report_chunk_sent_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_received",
        timing.guest_trace_report_chunk_received_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_reports",
        timing.guest_trace_report_chunk_report_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_rows",
        timing.guest_trace_report_chunk_row_count(),
    );
    timings.record_count(
        "guest_trace_report_chunk_max_queued",
        timing.guest_trace_report_chunk_max_queued_count(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_capacity",
        timing.guest_trace_runner_report_buffer_capacity(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_max_capacity",
        timing.guest_trace_runner_report_buffer_max_capacity(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_excess_capacity",
        timing.guest_trace_runner_report_buffer_excess_capacity(),
    );
    timings.record_count(
        "guest_trace_report_buffer_capacity",
        timing.guest_trace_report_buffer_capacity(),
    );
    timings.record_count(
        "guest_trace_report_buffer_max_capacity",
        timing.guest_trace_report_buffer_max_capacity(),
    );
    timings.record_count(
        "guest_trace_report_buffer_excess_capacity",
        timing.guest_trace_report_buffer_excess_capacity(),
    );
    timings.record_count(
        "guest_trace_report_record_size_bytes",
        timing.guest_trace_report_record_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_instruction_size_bytes",
        timing.guest_trace_report_instruction_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_register_write_list_size_bytes",
        timing.guest_trace_report_register_write_list_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_memory_access_list_size_bytes",
        timing.guest_trace_report_memory_access_list_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_precompile_access_list_size_bytes",
        timing.guest_trace_report_precompile_access_list_size_bytes(),
    );
    timings.record_count(
        "guest_trace_report_storage_bytes",
        timing.guest_trace_report_storage_bytes(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_capacity_bytes",
        timing.guest_trace_runner_report_buffer_capacity_bytes(),
    );
    timings.record_count(
        "guest_trace_runner_report_buffer_excess_bytes",
        timing.guest_trace_runner_report_buffer_excess_bytes(),
    );
    timings.record_count(
        "guest_trace_report_buffer_capacity_bytes",
        timing.guest_trace_report_buffer_capacity_bytes(),
    );
    timings.record_count(
        "guest_trace_report_buffer_excess_bytes",
        timing.guest_trace_report_buffer_excess_bytes(),
    );
    timings.record_count(
        "guest_trace_descriptor_rows",
        timing.guest_trace_descriptor_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_compact_rows",
        timing.guest_trace_descriptor_compact_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_wide_rows",
        timing.guest_trace_descriptor_wide_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_unpaired_values",
        timing.guest_trace_descriptor_unpaired_value_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_unpaired_high32_nonzero_values",
        timing.guest_trace_descriptor_unpaired_high32_nonzero_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_unpaired_high32_nonzero_rows",
        timing.guest_trace_descriptor_unpaired_high32_nonzero_row_count(),
    );
    timings.record_count(
        "guest_trace_descriptor_high32_stats_enabled",
        usize::from(timing.guest_trace_descriptor_high32_stats_enabled()),
    );
    let [descriptor_high32_a_values, descriptor_high32_b_values, descriptor_high32_c_values, descriptor_high32_a_payload_values, descriptor_high32_b_payload_values, descriptor_high32_store_payload_values, descriptor_high32_store_prev_value_values] =
        timing.guest_trace_descriptor_high32_field_counts();
    timings.record_count(
        "guest_trace_descriptor_high32_a_values",
        descriptor_high32_a_values,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_b_values",
        descriptor_high32_b_values,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_c_values",
        descriptor_high32_c_values,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_a_payload_values",
        descriptor_high32_a_payload_values,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_b_payload_values",
        descriptor_high32_b_payload_values,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_store_payload_values",
        descriptor_high32_store_payload_values,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_store_prev_value_values",
        descriptor_high32_store_prev_value_values,
    );
    let [descriptor_high32_rows_with_0_fields, descriptor_high32_rows_with_1_fields, descriptor_high32_rows_with_2_fields, descriptor_high32_rows_with_3_fields, descriptor_high32_rows_with_4_fields, descriptor_high32_rows_with_5_fields, descriptor_high32_rows_with_6_fields, descriptor_high32_rows_with_7_fields] =
        timing.guest_trace_descriptor_high32_row_field_histogram();
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_0_fields",
        descriptor_high32_rows_with_0_fields,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_1_fields",
        descriptor_high32_rows_with_1_fields,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_2_fields",
        descriptor_high32_rows_with_2_fields,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_3_fields",
        descriptor_high32_rows_with_3_fields,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_4_fields",
        descriptor_high32_rows_with_4_fields,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_5_fields",
        descriptor_high32_rows_with_5_fields,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_6_fields",
        descriptor_high32_rows_with_6_fields,
    );
    timings.record_count(
        "guest_trace_descriptor_high32_rows_with_7_fields",
        descriptor_high32_rows_with_7_fields,
    );
    timings.record_count(
        "guest_trace_single_row_reports",
        timing.guest_trace_single_row_report_count(),
    );
    timings.record_count(
        "guest_trace_multi_row_reports",
        timing.guest_trace_multi_row_report_count(),
    );
    timings.record_count(
        "guest_trace_pending_dma_reports",
        timing.guest_trace_pending_dma_report_count(),
    );
    timings.record_count(
        "guest_trace_amo_reports",
        timing.guest_trace_amo_report_count(),
    );
    timings.record_count(
        "guest_trace_store_conditional_reports",
        timing.guest_trace_store_conditional_report_count(),
    );
    timings.record_count(
        "guest_trace_external_op_rows",
        timing.guest_trace_external_op_row_count(),
    );
    timings.record_count(
        "guest_trace_external_op_runs",
        timing.guest_trace_external_op_run_count(),
    );
    timings.record_count(
        "guest_trace_external_op_max_run",
        timing.guest_trace_external_op_max_run_count(),
    );
    timings.record_count("guest_trace_copy_rows", timing.guest_trace_copy_row_count());
    timings.record_count(
        "guest_trace_copy_memory_source_rows",
        timing.guest_trace_copy_memory_source_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_indirect_memory_rows",
        timing.guest_trace_copy_indirect_memory_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_register_store_rows",
        timing.guest_trace_copy_register_store_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_memory_store_rows",
        timing.guest_trace_copy_memory_store_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_no_store_rows",
        timing.guest_trace_copy_no_store_row_count(),
    );
    timings.record_count(
        "guest_trace_copy_no_memory_rows",
        timing.guest_trace_copy_no_memory_row_count(),
    );
    timings.record_count("guest_trace_copy_runs", timing.guest_trace_copy_run_count());
    timings.record_count(
        "guest_trace_copy_max_run",
        timing.guest_trace_copy_max_run_count(),
    );
    timings.record_count("guest_trace_flag_rows", timing.guest_trace_flag_row_count());
    timings.record_count(
        "guest_trace_precompile_rows",
        timing.guest_trace_precompile_row_count(),
    );
    timings.record_count(
        "guest_trace_indirect_memory_rows",
        timing.guest_trace_indirect_memory_row_count(),
    );
    timings.record_count(
        "guest_trace_register_source_reads",
        timing.guest_trace_register_source_read_count(),
    );
    timings.record_count(
        "guest_trace_memory_source_reads",
        timing.guest_trace_memory_source_read_count(),
    );
    timings.record_count(
        "guest_trace_copy_source_memory_reads",
        timing.guest_trace_copy_source_memory_read_count(),
    );
    timings.record_count(
        "guest_trace_copy_source_indirect_reads",
        timing.guest_trace_copy_source_indirect_read_count(),
    );
    timings.record_count(
        "guest_trace_register_store_rows",
        timing.guest_trace_register_store_row_count(),
    );
    timings.record_count(
        "guest_trace_memory_store_rows",
        timing.guest_trace_memory_store_row_count(),
    );
    timings.record_count(
        "guest_trace_no_store_rows",
        timing.guest_trace_no_store_row_count(),
    );
    timings.record(
        "guest_trace_pending_send_wait",
        timing.guest_trace_pending_send_wait_duration(),
    );
    timings.record(
        "guest_trace_pending_receive_wait",
        timing.guest_trace_pending_receive_wait_duration(),
    );
    timings.record(
        "guest_trace_segment_send_wait",
        timing.guest_trace_segment_send_wait_duration(),
    );
    timings.record(
        "guest_trace_segment_receive_wait",
        timing.guest_trace_segment_receive_wait_duration(),
    );
    timings.record_count(
        "guest_trace_segment_replay_count",
        timing.guest_trace_segment_replay_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_workers",
        timing.guest_trace_parallel_lower_worker_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_dispatched",
        timing.guest_trace_parallel_lower_dispatched_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_received",
        timing.guest_trace_parallel_lower_received_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_emitted",
        timing.guest_trace_parallel_lower_emitted_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_max_reorder",
        timing.guest_trace_parallel_lower_max_reorder_count(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_snapshot_replay_count",
        timing.guest_trace_parallel_lower_snapshot_replay_count(),
    );
    timings.record(
        "guest_trace_parallel_lower_snapshot_replay",
        timing.guest_trace_parallel_lower_snapshot_replay_duration(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_report_elided_count",
        timing.guest_trace_parallel_lower_report_elided_count(),
    );
    timings.record(
        "guest_trace_parallel_lower_dispatch_wait",
        timing.guest_trace_parallel_lower_dispatch_wait_duration(),
    );
    timings.record(
        "guest_trace_parallel_lower_result_receive_wait",
        timing.guest_trace_parallel_lower_result_receive_wait_duration(),
    );
    timings.record_count(
        "guest_trace_parallel_lower_dispatch_blocked_count",
        timing.guest_trace_parallel_lower_dispatch_blocked_count(),
    );
    timings.record(
        "guest_device_source_build",
        timing.guest_device_source_build_duration(),
    );
    timings.record(
        "guest_device_source_descriptor_upload",
        timing.guest_device_source_descriptor_upload_duration(),
    );
    timings.record_count(
        "guest_device_source_descriptor_upload_bytes",
        timing.guest_device_source_descriptor_upload_byte_count(),
    );
    timings.record_count(
        "guest_device_source_descriptor_upload_words",
        timing.guest_device_source_descriptor_upload_word_count(),
    );
    timings.record_count(
        "guest_device_source_descriptor_upload_rows",
        timing.guest_device_source_descriptor_upload_row_count(),
    );
    timings.record_count(
        "guest_device_source_descriptor_stream_ingress",
        timing.guest_device_source_descriptor_stream_ingress_count(),
    );
    timings.record(
        "guest_device_source_trace_expand",
        timing.guest_device_source_trace_expand_duration(),
    );
    timings.record_count(
        "guest_stage_source_retention_attempts",
        timing.guest_stage_source_retention_attempt_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_retained",
        timing.guest_stage_source_retention_retained_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_rejected",
        timing.guest_stage_source_retention_rejected_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_retained_bytes",
        timing.guest_stage_source_retention_retained_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_rejected_bytes",
        timing.guest_stage_source_retention_rejected_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_max_retained_bytes",
        timing.guest_stage_source_retention_max_retained_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_max_rejected_bytes",
        timing.guest_stage_source_retention_max_rejected_byte_count(),
    );
    timings.record_count(
        "guest_stage_source_retention_limit_bytes",
        timing.guest_stage_source_retention_limit_byte_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_attempts",
        timing.guest_descriptor_buffer_retention_attempt_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_retained",
        timing.guest_descriptor_buffer_retention_retained_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_rejected",
        timing.guest_descriptor_buffer_retention_rejected_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_retained_bytes",
        timing.guest_descriptor_buffer_retention_retained_byte_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_rejected_bytes",
        timing.guest_descriptor_buffer_retention_rejected_byte_count(),
    );
    timings.record_count(
        "guest_descriptor_buffer_retention_limit_bytes",
        timing.guest_descriptor_buffer_retention_limit_byte_count(),
    );
    timings.record(
        "guest_regular_constraints",
        timing.guest_regular_constraint_duration(),
    );
    timings.record("guest_regular_hints", timing.guest_regular_hint_duration());
    timings.record("guest_stage_commit", timing.guest_stage_commit_duration());
    timings.record(
        "guest_stage_trace_extract",
        timing.guest_stage_trace_extract_duration(),
    );
    timings.record(
        "guest_stage_leaf_extend_work",
        timing.guest_stage_leaf_extend_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_work",
        timing.guest_stage_leaf_setup_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_prepare",
        timing.guest_stage_leaf_setup_prepare_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_output_alloc",
        timing.guest_stage_leaf_setup_output_alloc_duration(),
    );
    timings.record(
        "guest_stage_leaf_setup_workspace_alloc",
        timing.guest_stage_leaf_setup_workspace_alloc_duration(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_output_alloc_bytes",
        timing.guest_stage_leaf_setup_output_alloc_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_workspace_alloc_bytes",
        timing.guest_stage_leaf_setup_workspace_alloc_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_output_alloc_count",
        timing.guest_stage_leaf_setup_output_alloc_count(),
    );
    timings.record_count(
        "guest_stage_leaf_output_cache_hits",
        timing.guest_stage_leaf_output_cache_hit_count(),
    );
    timings.record_count(
        "guest_stage_leaf_output_cache_misses",
        timing.guest_stage_leaf_output_cache_miss_count(),
    );
    timings.record_count(
        "guest_stage_leaf_setup_workspace_alloc_count",
        timing.guest_stage_leaf_setup_workspace_alloc_count(),
    );
    timings.record(
        "guest_stage_leaf_upload_work",
        timing.guest_stage_leaf_upload_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_kernel_work",
        timing.guest_stage_leaf_kernel_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_download_work",
        timing.guest_stage_leaf_download_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_validate_work",
        timing.guest_stage_leaf_validate_work_duration(),
    );
    timings.record(
        "guest_stage_leaf_hash_work",
        timing.guest_stage_leaf_hash_work_duration(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_rows",
        timing.guest_stage_leaf_hash_row_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_bytes",
        timing.guest_stage_leaf_hash_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity2_rows",
        timing.guest_stage_leaf_hash_arity2_row_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity2_bytes",
        timing.guest_stage_leaf_hash_arity2_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity4_rows",
        timing.guest_stage_leaf_hash_arity4_row_count(),
    );
    timings.record_count(
        "guest_stage_leaf_hash_arity4_bytes",
        timing.guest_stage_leaf_hash_arity4_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_calls",
        timing.guest_stage_leaf_coset_extend_call_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_output_bytes",
        timing.guest_stage_leaf_coset_extend_output_byte_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_columns",
        timing.guest_stage_leaf_coset_extend_column_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_max_columns",
        timing.guest_stage_leaf_coset_extend_max_column_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_ntt_launches",
        timing.guest_stage_leaf_coset_extend_ntt_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_bit_reverse_launches",
        timing.guest_stage_leaf_coset_extend_bit_reverse_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_ntt_stage_launches",
        timing.guest_stage_leaf_coset_extend_ntt_stage_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_ntt_block_twiddle_launches",
        timing.guest_stage_leaf_coset_extend_ntt_block_twiddle_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_normalize_launches",
        timing.guest_stage_leaf_coset_extend_normalize_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_pack_launches",
        timing.guest_stage_leaf_coset_extend_pack_launch_count(),
    );
    timings.record_count(
        "guest_stage_leaf_coset_extend_unpack_launches",
        timing.guest_stage_leaf_coset_extend_unpack_launch_count(),
    );
    timings.record(
        "guest_stage_tree_commit_work",
        timing.guest_stage_tree_commit_work_duration(),
    );
    timings.record(
        "guest_stage_tree_commit_checkpoint_work",
        timing.guest_stage_tree_commit_checkpoint_work_duration(),
    );
    timings.record(
        "guest_stage_tree_commit_root_work",
        timing.guest_stage_tree_commit_root_work_duration(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_count",
        timing.guest_stage_tree_commit_root_count(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_bytes",
        timing.guest_stage_tree_commit_root_byte_count(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_materialization_groups",
        timing.guest_stage_tree_commit_root_materialization_group_count(),
    );
    timings.record_count(
        "guest_stage_tree_commit_root_materialization_max_group_size",
        timing.guest_stage_tree_commit_root_materialization_max_group_size(),
    );
    record_guest_stage_root_materialization_shape(
        timings,
        timing.guest_stage_tree_commit_root_count(),
        timing.guest_stage_tree_commit_root_materialization_group_count(),
        timing.guest_stage_tree_commit_root_materialization_max_group_size(),
    );
    timings.record(
        "guest_stage_tree_commit_retain_work",
        timing.guest_stage_tree_commit_retain_work_duration(),
    );
    for stage_timing in timing.guest_stage_timings() {
        let stage_index = stage_timing.stage_index();
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_extend_work"),
            stage_timing.leaf_extend_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_work"),
            stage_timing.leaf_setup_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_prepare"),
            stage_timing.leaf_setup_prepare_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_output_alloc"),
            stage_timing.leaf_setup_output_alloc_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_workspace_alloc"),
            stage_timing.leaf_setup_workspace_alloc_duration(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_output_alloc_bytes"),
            stage_timing.leaf_setup_output_alloc_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_workspace_alloc_bytes"),
            stage_timing.leaf_setup_workspace_alloc_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_output_alloc_count"),
            stage_timing.leaf_setup_output_alloc_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_output_cache_hits"),
            stage_timing.leaf_output_cache_hit_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_output_cache_misses"),
            stage_timing.leaf_output_cache_miss_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_setup_workspace_alloc_count"),
            stage_timing.leaf_setup_workspace_alloc_count(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_upload_work"),
            stage_timing.leaf_upload_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_kernel_work"),
            stage_timing.leaf_kernel_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_download_work"),
            stage_timing.leaf_download_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_validate_work"),
            stage_timing.leaf_validate_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_work"),
            stage_timing.leaf_hash_work_duration(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_rows"),
            stage_timing.leaf_hash_row_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_bytes"),
            stage_timing.leaf_hash_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity2_rows"),
            stage_timing.leaf_hash_arity2_row_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity2_bytes"),
            stage_timing.leaf_hash_arity2_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity4_rows"),
            stage_timing.leaf_hash_arity4_row_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_hash_arity4_bytes"),
            stage_timing.leaf_hash_arity4_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_calls"),
            stage_timing.leaf_coset_extend_call_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_output_bytes"),
            stage_timing.leaf_coset_extend_output_byte_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_columns"),
            stage_timing.leaf_coset_extend_column_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_max_columns"),
            stage_timing.leaf_coset_extend_max_column_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_ntt_launches"),
            stage_timing.leaf_coset_extend_ntt_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_bit_reverse_launches"),
            stage_timing.leaf_coset_extend_bit_reverse_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_ntt_stage_launches"),
            stage_timing.leaf_coset_extend_ntt_stage_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_ntt_block_twiddle_launches"),
            stage_timing.leaf_coset_extend_ntt_block_twiddle_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_normalize_launches"),
            stage_timing.leaf_coset_extend_normalize_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_pack_launches"),
            stage_timing.leaf_coset_extend_pack_launch_count(),
        );
        timings.record_count_dynamic(
            format!("guest_stage_{stage_index}_leaf_coset_extend_unpack_launches"),
            stage_timing.leaf_coset_extend_unpack_launch_count(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_work"),
            stage_timing.tree_commit_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_checkpoint_work"),
            stage_timing.tree_commit_checkpoint_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_root_work"),
            stage_timing.tree_commit_root_work_duration(),
        );
        timings.record_dynamic(
            format!("guest_stage_{stage_index}_tree_commit_retain_work"),
            stage_timing.tree_commit_retain_work_duration(),
        );
    }
}

fn record_guest_stage_root_materialization_shape(
    timings: &mut TimingRecorder,
    root_count: usize,
    group_count: usize,
    max_group_size: usize,
) {
    let avg_group_size_milli = if group_count == 0 {
        0
    } else {
        root_count.saturating_mul(1000) / group_count
    };
    let needs_cross_segment_pipeline =
        usize::from(root_count > 1 && group_count == root_count && max_group_size <= 1);
    timings.record_count(
        "guest_stage_tree_commit_root_materialization_avg_group_size_milli",
        avg_group_size_milli,
    );
    timings.record_count(
        "guest_stage_tree_commit_root_materialization_needs_cross_segment_pipeline",
        needs_cross_segment_pipeline,
    );
}

fn record_guest_trace_sampled_duration_counts(
    timings: &mut TimingRecorder,
    name: &'static str,
    duration: Duration,
    sample_count: usize,
) {
    if sample_count == 0 {
        return;
    }
    let sampled_ns = duration_ns(duration);
    timings.record_count_dynamic(format!("{name}_sampled_ns"), sampled_ns);
    timings.record_count_dynamic(format!("{name}_avg_sample_ns"), sampled_ns / sample_count);
}

fn duration_ns(duration: Duration) -> usize {
    usize::try_from(duration.as_nanos()).unwrap_or(usize::MAX)
}

#[cfg(test)]
mod tests {
    use super::super::timing::{write_timing_summary, TimingRecorder};
    use super::{
        record_guest_stage_root_materialization_shape, record_guest_trace_sampled_duration_counts,
    };
    use std::time::Duration;

    #[test]
    fn guest_root_materialization_shape_flags_cross_segment_pipeline_need() {
        let mut timings = TimingRecorder::new(true);

        record_guest_stage_root_materialization_shape(&mut timings, 23, 23, 1);

        let mut stdout = Vec::new();
        write_timing_summary(&mut stdout, &timings);
        let stdout = String::from_utf8(stdout).expect("timing output should be utf-8");

        for expected in [
            "timing_guest_stage_tree_commit_root_materialization_avg_group_size_milli=1000\n",
            "timing_guest_stage_tree_commit_root_materialization_needs_cross_segment_pipeline=1\n",
        ] {
            assert!(stdout.contains(expected), "missing {expected} in {stdout}");
        }
    }

    #[test]
    fn guest_root_materialization_shape_keeps_batched_groups_clear() {
        let mut timings = TimingRecorder::new(true);

        record_guest_stage_root_materialization_shape(&mut timings, 24, 6, 4);

        let mut stdout = Vec::new();
        write_timing_summary(&mut stdout, &timings);
        let stdout = String::from_utf8(stdout).expect("timing output should be utf-8");

        for expected in [
            "timing_guest_stage_tree_commit_root_materialization_avg_group_size_milli=4000\n",
            "timing_guest_stage_tree_commit_root_materialization_needs_cross_segment_pipeline=0\n",
        ] {
            assert!(stdout.contains(expected), "missing {expected} in {stdout}");
        }
    }

    #[test]
    fn guest_trace_sampled_detail_counts_keep_submillisecond_resolution() {
        let mut timings = TimingRecorder::new(true);

        record_guest_trace_sampled_duration_counts(
            &mut timings,
            "guest_trace_report",
            Duration::from_nanos(750),
            3,
        );

        let mut stdout = Vec::new();
        write_timing_summary(&mut stdout, &timings);
        let stdout = String::from_utf8(stdout).expect("timing output should be utf-8");

        for expected in [
            "timing_guest_trace_report_sampled_ns=750\n",
            "timing_guest_trace_report_avg_sample_ns=250\n",
        ] {
            assert!(stdout.contains(expected), "missing {expected} in {stdout}");
        }
    }

    #[test]
    fn guest_trace_sampled_detail_counts_skip_without_samples() {
        let mut timings = TimingRecorder::new(true);

        record_guest_trace_sampled_duration_counts(
            &mut timings,
            "guest_trace_report",
            Duration::from_nanos(750),
            0,
        );

        let mut stdout = Vec::new();
        write_timing_summary(&mut stdout, &timings);
        let stdout = String::from_utf8(stdout).expect("timing output should be utf-8");

        assert!(!stdout.contains("guest_trace_report_sampled_ns"));
        assert!(!stdout.contains("guest_trace_report_avg_sample_ns"));
    }
}
