use super::timing::TimingRecorder;

pub(super) fn record_proof_artifact_timing(
    timings: &mut TimingRecorder,
    timing: &lzvm_prover::WitnessProofArtifactTiming,
) {
    timings.record("finish_query_plan", timing.query_plan);
    timings.record("finish_constant_opening", timing.constant_opening);
    timings.record("finish_witness_opening", timing.witness_opening);
    timings.record_count(
        "finish_witness_opening_query_count",
        timing.witness_opening_query_count,
    );
    timings.record_count(
        "finish_witness_opening_query_unit_count",
        timing.witness_opening_query_unit_count,
    );
    timings.record_count(
        "finish_witness_opening_single_query_unit_count",
        timing.witness_opening_single_query_unit_count,
    );
    timings.record_count(
        "finish_witness_opening_max_queries_per_unit",
        timing.witness_opening_max_queries_per_unit,
    );
    timings.record_count(
        "finish_witness_opening_stage_count",
        timing.witness_opening_stage_count,
    );
    timings.record_count(
        "finish_witness_opening_retained_source_count",
        timing.witness_opening_retained_source_count,
    );
    timings.record_count(
        "finish_witness_opening_external_source_count",
        timing.witness_opening_external_source_count,
    );
    timings.record_count(
        "finish_witness_opening_embedded_source_count",
        timing.witness_opening_embedded_source_count,
    );
    timings.record_count(
        "finish_witness_opening_missing_source_count",
        timing.witness_opening_missing_source_count,
    );
    timings.record_count(
        "finish_witness_opening_retained_leaf_digest_openings",
        timing.witness_opening_retained_leaf_digest_opening_count,
    );
    timings.record_count(
        "finish_witness_opening_retained_leaf_digest_rows",
        timing.witness_opening_retained_leaf_digest_opening_row_count,
    );
    timings.record_count(
        "finish_witness_opening_retained_parent_checkpoint_openings",
        timing.witness_opening_retained_parent_checkpoint_opening_count,
    );
    timings.record_count(
        "finish_witness_opening_retained_parent_checkpoint_rows",
        timing.witness_opening_retained_parent_checkpoint_opening_row_count,
    );
    timings.record(
        "finish_witness_external_source",
        timing.witness_external_source,
    );
    timings.record(
        "finish_witness_external_source_descriptor_upload",
        timing.witness_external_source_descriptor_upload,
    );
    timings.record_count(
        "finish_witness_external_source_descriptor_upload_bytes",
        timing.witness_external_source_descriptor_upload_byte_count,
    );
    timings.record_count(
        "finish_witness_external_source_descriptor_upload_words",
        timing.witness_external_source_descriptor_upload_word_count,
    );
    timings.record_count(
        "finish_witness_external_source_descriptor_upload_rows",
        timing.witness_external_source_descriptor_upload_row_count,
    );
    timings.record(
        "finish_witness_external_source_trace_expand",
        timing.witness_external_source_trace_expand,
    );
    timings.record("finish_witness_opening_setup", timing.witness_opening_setup);
    timings.record(
        "finish_witness_opening_leaf_extend",
        timing.witness_opening_leaf_extend,
    );
    timings.record(
        "finish_witness_opening_leaf_hash",
        timing.witness_opening_leaf_hash,
    );
    timings.record_count(
        "finish_witness_opening_leaf_hash_rows",
        timing.witness_opening_leaf_hash_row_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_hash_bytes",
        timing.witness_opening_leaf_hash_byte_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_hash_arity2_rows",
        timing.witness_opening_leaf_hash_arity2_row_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_hash_arity2_bytes",
        timing.witness_opening_leaf_hash_arity2_byte_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_hash_arity4_rows",
        timing.witness_opening_leaf_hash_arity4_row_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_hash_arity4_bytes",
        timing.witness_opening_leaf_hash_arity4_byte_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_calls",
        timing.witness_opening_leaf_coset_extend_call_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_output_bytes",
        timing.witness_opening_leaf_coset_extend_output_byte_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_columns",
        timing.witness_opening_leaf_coset_extend_column_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_max_columns",
        timing.witness_opening_leaf_coset_extend_max_column_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_ntt_launches",
        timing.witness_opening_leaf_coset_extend_ntt_launch_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_bit_reverse_launches",
        timing.witness_opening_leaf_coset_extend_bit_reverse_launch_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_ntt_stage_launches",
        timing.witness_opening_leaf_coset_extend_ntt_stage_launch_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_ntt_block_twiddle_launches",
        timing.witness_opening_leaf_coset_extend_ntt_block_twiddle_launch_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_normalize_launches",
        timing.witness_opening_leaf_coset_extend_normalize_launch_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_pack_launches",
        timing.witness_opening_leaf_coset_extend_pack_launch_count,
    );
    timings.record_count(
        "finish_witness_opening_leaf_coset_extend_unpack_launches",
        timing.witness_opening_leaf_coset_extend_unpack_launch_count,
    );
    timings.record(
        "finish_witness_opening_path_parent_hash",
        timing.witness_opening_path_parent_hash,
    );
    timings.record(
        "finish_witness_opening_path_parent_hash_recomputed",
        timing.witness_opening_path_parent_hash_recomputed,
    );
    timings.record(
        "finish_witness_opening_path_parent_hash_retained_leaf_digest",
        timing.witness_opening_path_parent_hash_retained_leaf_digest,
    );
    timings.record(
        "finish_witness_opening_path_parent_hash_retained_parent_checkpoint_prefix",
        timing.witness_opening_path_parent_hash_retained_parent_checkpoint_prefix,
    );
    timings.record(
        "finish_witness_opening_path_parent_hash_retained_parent_checkpoint_suffix",
        timing.witness_opening_path_parent_hash_retained_parent_checkpoint_suffix,
    );
    timings.record_count(
        "finish_witness_opening_path_parent_hash_rows",
        timing.witness_opening_path_parent_hash_row_count,
    );
    timings.record_count(
        "finish_witness_opening_path_parent_hash_bytes",
        timing.witness_opening_path_parent_hash_byte_count,
    );
    timings.record_count(
        "finish_witness_opening_path_parent_hash_launches",
        timing.witness_opening_path_parent_hash_launch_count,
    );
    record_path_parent_hash_work_split(
        timings,
        "finish_witness_opening_path_parent_hash",
        [
            (
                "recomputed",
                timing.witness_opening_path_parent_hash_recomputed_row_count,
                timing.witness_opening_path_parent_hash_recomputed_byte_count,
                timing.witness_opening_path_parent_hash_recomputed_launch_count,
            ),
            (
                "retained_leaf_digest",
                timing.witness_opening_path_parent_hash_retained_leaf_digest_row_count,
                timing.witness_opening_path_parent_hash_retained_leaf_digest_byte_count,
                timing.witness_opening_path_parent_hash_retained_leaf_digest_launch_count,
            ),
            (
                "retained_parent_checkpoint_prefix",
                timing
                    .witness_opening_path_parent_hash_retained_parent_checkpoint_prefix_row_count,
                timing
                    .witness_opening_path_parent_hash_retained_parent_checkpoint_prefix_byte_count,
                timing
                    .witness_opening_path_parent_hash_retained_parent_checkpoint_prefix_launch_count,
            ),
            (
                "retained_parent_checkpoint_suffix",
                timing
                    .witness_opening_path_parent_hash_retained_parent_checkpoint_suffix_row_count,
                timing
                    .witness_opening_path_parent_hash_retained_parent_checkpoint_suffix_byte_count,
                timing
                    .witness_opening_path_parent_hash_retained_parent_checkpoint_suffix_launch_count,
            ),
        ],
    );
    record_count_per_unit(
        timings,
        "finish_witness_opening_path_parent_hash_rows_per_query",
        timing.witness_opening_path_parent_hash_row_count,
        timing.witness_opening_query_count,
    );
    record_count_per_unit(
        timings,
        "finish_witness_opening_path_parent_hash_rows_per_stage",
        timing.witness_opening_path_parent_hash_row_count,
        timing.witness_opening_stage_count,
    );
    record_count_per_unit(
        timings,
        "finish_witness_opening_path_parent_hash_launches_per_stage",
        timing.witness_opening_path_parent_hash_launch_count,
        timing.witness_opening_stage_count,
    );
    timings.record("finish_witness_opening_path", timing.witness_opening_path);
    timings.record(
        "finish_witness_opening_row_values",
        timing.witness_opening_row_values,
    );
    timings.record(
        "finish_witness_opening_row_value_source_extend",
        timing.witness_opening_row_values_source_extend,
    );
    timings.record(
        "finish_witness_opening_row_value_source_download",
        timing.witness_opening_row_values_source_download,
    );
    timings.record(
        "finish_witness_opening_row_value_device_download",
        timing.witness_opening_row_values_device_download,
    );
    timings.record_count(
        "finish_witness_opening_row_values_device_rows",
        timing.witness_opening_row_values_device_row_count,
    );
    timings.record_count(
        "finish_witness_opening_row_values_device_download_batches",
        timing.witness_opening_row_values_device_download_batch_count,
    );
    timings.record_count(
        "finish_witness_opening_row_values_source_rows",
        timing.witness_opening_row_values_source_row_count,
    );
    timings.record_count(
        "finish_witness_opening_row_values_words",
        timing.witness_opening_row_values_word_count,
    );
    timings.record_count(
        "finish_witness_opening_row_values_bytes",
        timing.witness_opening_row_values_byte_count,
    );
    for stage_timing in &timing.witness_stage_external_source {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_external_source",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening_setup {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_setup",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening_leaf_extend {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_extend",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening_leaf_hash {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_hash",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_work in &timing.witness_stage_opening_work {
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_retained_source_count",
                stage_work.stage_index
            ),
            stage_work.retained_source_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_external_source_count",
                stage_work.stage_index
            ),
            stage_work.external_source_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_embedded_source_count",
                stage_work.stage_index
            ),
            stage_work.embedded_source_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_missing_source_count",
                stage_work.stage_index
            ),
            stage_work.missing_source_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_retained_leaf_digest_openings",
                stage_work.stage_index
            ),
            stage_work.retained_leaf_digest_opening_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_retained_leaf_digest_rows",
                stage_work.stage_index
            ),
            stage_work.retained_leaf_digest_opening_row_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_retained_parent_checkpoint_openings",
                stage_work.stage_index
            ),
            stage_work.retained_parent_checkpoint_opening_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_retained_parent_checkpoint_rows",
                stage_work.stage_index
            ),
            stage_work.retained_parent_checkpoint_opening_row_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_hash_rows",
                stage_work.stage_index
            ),
            stage_work.leaf_hash_row_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_hash_bytes",
                stage_work.stage_index
            ),
            stage_work.leaf_hash_byte_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_hash_arity2_rows",
                stage_work.stage_index
            ),
            stage_work.leaf_hash_arity2_row_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_hash_arity2_bytes",
                stage_work.stage_index
            ),
            stage_work.leaf_hash_arity2_byte_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_hash_arity4_rows",
                stage_work.stage_index
            ),
            stage_work.leaf_hash_arity4_row_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_hash_arity4_bytes",
                stage_work.stage_index
            ),
            stage_work.leaf_hash_arity4_byte_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_calls",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_call_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_output_bytes",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_output_byte_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_columns",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_column_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_max_columns",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_max_column_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_ntt_launches",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_ntt_launch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_bit_reverse_launches",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_bit_reverse_launch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_ntt_stage_launches",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_ntt_stage_launch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_ntt_block_twiddle_launches",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_ntt_block_twiddle_launch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_normalize_launches",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_normalize_launch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_pack_launches",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_pack_launch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_leaf_coset_extend_unpack_launches",
                stage_work.stage_index
            ),
            stage_work.leaf_coset_extend_unpack_launch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash_rows",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash_row_count,
        );
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash,
        );
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash_recomputed",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash_recomputed,
        );
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash_retained_leaf_digest",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash_retained_leaf_digest,
        );
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash_retained_parent_checkpoint_prefix",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash_retained_parent_checkpoint_prefix,
        );
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash_retained_parent_checkpoint_suffix",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash_retained_parent_checkpoint_suffix,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash_bytes",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash_byte_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path_parent_hash_launches",
                stage_work.stage_index
            ),
            stage_work.path_parent_hash_launch_count,
        );
        record_path_parent_hash_work_split(
            timings,
            &format!(
                "finish_witness_stage_{}_opening_path_parent_hash",
                stage_work.stage_index
            ),
            [
                (
                    "recomputed",
                    stage_work.path_parent_hash_recomputed_row_count,
                    stage_work.path_parent_hash_recomputed_byte_count,
                    stage_work.path_parent_hash_recomputed_launch_count,
                ),
                (
                    "retained_leaf_digest",
                    stage_work.path_parent_hash_retained_leaf_digest_row_count,
                    stage_work.path_parent_hash_retained_leaf_digest_byte_count,
                    stage_work.path_parent_hash_retained_leaf_digest_launch_count,
                ),
                (
                    "retained_parent_checkpoint_prefix",
                    stage_work.path_parent_hash_retained_parent_checkpoint_prefix_row_count,
                    stage_work.path_parent_hash_retained_parent_checkpoint_prefix_byte_count,
                    stage_work.path_parent_hash_retained_parent_checkpoint_prefix_launch_count,
                ),
                (
                    "retained_parent_checkpoint_suffix",
                    stage_work.path_parent_hash_retained_parent_checkpoint_suffix_row_count,
                    stage_work.path_parent_hash_retained_parent_checkpoint_suffix_byte_count,
                    stage_work.path_parent_hash_retained_parent_checkpoint_suffix_launch_count,
                ),
            ],
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_values_device_rows",
                stage_work.stage_index
            ),
            stage_work.row_values_device_row_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_values_device_download_batches",
                stage_work.stage_index
            ),
            stage_work.row_values_device_download_batch_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_values_source_rows",
                stage_work.stage_index
            ),
            stage_work.row_values_source_row_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_values_words",
                stage_work.stage_index
            ),
            stage_work.row_values_word_count,
        );
        timings.record_count_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_values_bytes",
                stage_work.stage_index
            ),
            stage_work.row_values_byte_count,
        );
    }
    for stage_timing in &timing.witness_stage_opening_path {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_path",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening_row_values {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_values",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening_row_value_source_extend {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_value_source_extend",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening_row_value_source_download {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_value_source_download",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening_row_value_device_download {
        timings.record_dynamic(
            format!(
                "finish_witness_stage_{}_opening_row_value_device_download",
                stage_timing.stage_index
            ),
            stage_timing.duration,
        );
    }
    for stage_timing in &timing.witness_stage_opening {
        timings.record_dynamic(
            format!("finish_witness_stage_{}_opening", stage_timing.stage_index),
            stage_timing.duration,
        );
    }
    timings.record("finish_fri_opening", timing.fri_opening);
    timings.record(
        "finish_fri_opening_unit_build",
        timing.fri_opening_unit_build,
    );
    timings.record(
        "finish_fri_opening_layer_tree",
        timing.fri_opening_layer_tree,
    );
    timings.record("finish_fri_opening_query", timing.fri_opening_query);
    timings.record("finish_fri_opening_fold", timing.fri_opening_fold);
    timings.record(
        "finish_fri_transcript_unit_build",
        timing.fri_transcript_unit_build,
    );
    timings.record(
        "finish_fri_transcript_layer_tree",
        timing.fri_transcript_layer_tree,
    );
    timings.record("finish_fri_transcript_fold", timing.fri_transcript_fold);
    timings.record("finish_contribution_segment", timing.contribution_segment);
    timings.record("finish_contribution_verify", timing.contribution_verify);
    timings.record(
        "finish_contribution_challenge",
        timing.contribution_challenge,
    );
    timings.record_count(
        "finish_fri_opening_unit_count",
        timing.fri_opening_unit_count,
    );
    timings.record_count(
        "finish_fri_opening_layer_count",
        timing.fri_opening_layer_count,
    );
    timings.record_count(
        "finish_fri_opening_query_count",
        timing.fri_opening_query_count,
    );
    timings.record_count(
        "finish_fri_transcript_unit_count",
        timing.fri_transcript_unit_count,
    );
    timings.record_count(
        "finish_fri_transcript_layer_count",
        timing.fri_transcript_layer_count,
    );
}

fn record_path_parent_hash_work_split(
    timings: &mut TimingRecorder,
    prefix: &str,
    splits: [(&'static str, usize, usize, usize); 4],
) {
    for (suffix, rows, bytes, launches) in splits {
        timings.record_count_dynamic(format!("{prefix}_{suffix}_rows"), rows);
        timings.record_count_dynamic(format!("{prefix}_{suffix}_bytes"), bytes);
        timings.record_count_dynamic(format!("{prefix}_{suffix}_launches"), launches);
        record_count_per_unit_dynamic(
            timings,
            format!("{prefix}_{suffix}_rows_per_launch"),
            rows,
            launches,
        );
        record_count_per_unit_dynamic(
            timings,
            format!("{prefix}_{suffix}_bytes_per_launch"),
            bytes,
            launches,
        );
    }
}

fn record_count_per_unit_dynamic(
    timings: &mut TimingRecorder,
    name: String,
    numerator: usize,
    denominator: usize,
) {
    if denominator == 0 {
        return;
    }
    timings.record_count_dynamic(name, numerator / denominator);
}

fn record_count_per_unit(
    timings: &mut TimingRecorder,
    name: &'static str,
    numerator: usize,
    denominator: usize,
) {
    if denominator == 0 {
        return;
    }
    timings.record_count(name, numerator / denominator);
}
